name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*.*.*a*"
      - "v*.*.*b*"
      - "v*.*.*rc*"
    paths-ignore:
      - "**.md"
      - ".git*"
      - "docs/**"
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".git*"
      - "docs/**"

env:
  CI_PATH: '/home/mnt/platform_ci/GitHub/${{ github.repository }}/${{ github.run_number }}'
  PYTHON_VERSION: "3.10.9"
  LAZYLLM_DEFAULT_RECENT_K: 20

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{
    github.event_name == 'pull_request_target' && github.event.pull_request.title || github.ref }}
  cancel-in-progress: true

jobs:
  clone:
    if: |
      always()
      && !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.pull_request.title, '[skip ci]')
    runs-on: dya_test
    outputs:
      changed_files: ${{ steps.changed_files_yaml.outputs.all_changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Get changed files
        id: changed_files_yaml
        uses: tj-actions/changed-files@v47

      - name: List all changed files
        run: |
          echo "ALL_CHANGED_FILES:"
          for file in ${{ steps.changed_files_yaml.outputs.all_changed_files }}; do
            echo "$file"
          done
          echo ""

      - name: Fetch base branch for PR
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

      - name: Build doc
        run: |
          set -e
          pip install -r requirements.txt
          pip install -r docs/requirements.txt
          LAZYLLM_INIT_DOC=True python docs/add_docstrings.py

      - name: Setup CI directory
        run: |
          set -ex
          echo ${{ env.CI_PATH }}
          mkdir -p ${{ env.CI_PATH }}
          rm -rf ${{ env.CI_PATH }}/* ${{ env.CI_PATH }}/.[!.]*
          mv $GITHUB_WORKSPACE/* $GITHUB_WORKSPACE/.[!.]* ${{ env.CI_PATH }}/
          cd ${{ env.CI_PATH }}
          pip install -r tests/requirements.txt
          pip install -r tests/requirements_linux.txt

  basic_test:
    runs-on: dya_test
    needs: [ clone ]
    if: always() && needs.clone.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      - name: Install package in editable mode
        run: pip install -e .

      - name: RunTests
        uses: ./.github/actions/run_tests
        with:
          working_directory: ${{ env.CI_PATH }}
          changed_files: ${{ needs.clone.outputs.changed_files }}
          markers: "not skip_on_linux"
          tests_dir: "tests/basic_tests"
          launcher: "empty"
          nproc: 4
